# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8deecd763ca5f3fd8b8d8815d57d98716d89dafc18bf0c81b26f08ebdea85d8b9d8737aabf8584be0aa7a50bf2f1b6eb846a1b68bde5e0453f1546e4e90c4d16

test:
  secret_key_base: 9568e202e2d9c167d1baba1f63b60c6d468813f7c39081e07f3d1195bc22344d7f208a328bd3077399668c4c5c3023c71554b5064f578fbbf657c55d304fedb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
